### ISSUE TITLE
not working with node 12 and process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;

### ISSUE THREAD

**Issue by nfasoli** [syedhussim/node-sapb1#1]
with sslValidateCertificate: 'false' not working with node 12.

Fully working with 10

Thanks
Nicola

**Comment by ngurahyudi** [comment]
> with sslValidateCertificate: 'false' not working with node 12.
> 
> Fully working with 10
> 
> Thanks
> Nicola

please create a file at root of your project folder (ex. **.openssl_allow_tls1.0.cnf**)
paste this 
```
openssl_conf = openssl_init

[openssl_init]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
CipherString = DEFAULT@SECLEVEL=1
```


then in your nodemon.json
![image](https://user-images.githubusercontent.com/16011522/98086365-9b680280-1eb9-11eb-8f9d-dbcc5efadee9.png)

**Comment by ngurahyudi** [comment]
can you explain how to make it awaitable? because i need to save the response data to the log file

**Comment by syedhussim** [comment]
Hi  ngurahyudi,

You will need to wrap your code around a Promise. Do you need to log the resource data?

**Comment by ngurahyudi** [comment]
> Hi ngurahyudi,
> 
> You will need to wrap your code around a Promise. Do you need to log the resource data?

actually I need to log the response from **creating a service** and save it into database, can You make me a sample code because I'm not familiar with callbacks, I use async/await function and using NestJS framework.. 1 more question, can You make the typescript version of this awesome library? :)

**Comment by ngurahyudi** [comment]
> > Hi ngurahyudi,
> > You will need to wrap your code around a Promise. Do you need to log the resource data?
> 
> actually I need to log the response from **creating a service** and save it into database, can You make me a sample code because I'm not familiar with callbacks, I use async/await function and using NestJS framework.. 1 more question, can You make the typescript version of this awesome library? :)

I got this by following your advice, now the request are awaitable! awesome!
many thanks brother, you saved my day! :) 👍
